version: '3.9'

services:

  mr-pdf-args:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pdf:/app/pdf
    command:
      - bash
      - -c
      - |
        npx mr-pdf-args --initialDocURLs="https://v1.docusaurus.io/docs/en/installation" --paginationSelector=".docs-prevnext > a.docs-next" --excludeSelectors=".fixedHeaderContainer,footer.nav-footer,#docsNav,nav.onPageNav,a.edit-page-link,div.docs-prevnext" --cssStyle=".navPusher {padding-top: 0;}" --contentSelector="article" --puppeteerArgs="--no-sandbox" --outputPDFFilename="/app/pdf/output.pdf"
